
version: 2


sources:
  - name: Northwind
    description: "Source contenant les tables Northwind"

    tables:
    - name: customers
      description: "Informations sur les clients"

    - name: employees
      description: "Informations sur les employés"

    - name: orders
      description: "Commandes passées par les clients"

    - name: order_details
      description: "Détails des lignes de commande"

    - name: categories
      description: "Catalogue des produits"

    - name: suppliers
      description: "Fournisseurs des produits"

    - name: shippers
      description: "Transporteurs des commandes"
